### ISSUE TITLE
My Comments

### ISSUE THREAD

**Issue by zjedwin** [rishaythegreat/pwp-capstones#1]
Here are a list of the errors that you have in your code. Please correct these and run again:

Line 1:
`def init(self, name, email):`
should be
`def __init__(self, name, email):`

Line 14:
`def repr(self):`
should be
`def __repr__(self):`

Line 17:
`def eq(self, other_user):`
should be
`def __eq__(self, other_user):`

You should make similar changes to the ones above on the following lines
> 31, 39, 65, 68, 72, 79, 83, 88, and 92

Line 25:
`for valuein self.books.values():`
You need a space between `value` and `in`. So the line should be
`for value in self.books.values():`

Lines 53-54
```
if rating is not None and rating >= ) and rating <= 4:
    self.rating.append(rating
```
There are two errors here: You're comparing `rating` against a closing parenthesis and you're missing a closing parenthesis on the second line.

Line 72:
`def init(self, title, author, isbn))`
should be 
`def init(self, title, author, isbn):`

Line 80:
`return '{title} by {author}".format(title=self.title, author=self.author)`
You cannot begin with a single quote and end with a double quote or vice versa. Choose either single or double quotes and be consistent.

Line 104:
`def create_non_firction(self, title, subject, level, isbn):`
should be
`def create_non_fiction(self, title, subject, level, isbn):`

Line 110:
`user = self.users{email}`
You cannot access a dictionary that way. You want instead
`user = self.users[email]`

Line 123:
`def add_user(self, name, email, user_books=Noone):`
You misspell `None`. The line should be
`def add_user(self, name, email, user_books=None):`

Line 161:
`highest_ratings = )`
should be
`highest_ratings = 0`

The following line in your `populate.py` file
`Tome_Rater.print_catalog()`
should be
`Tome_Rater.print_book_catalog()`

The following line in your `populate.py` file
`Tome_Rater.print_users()`
should be
`Tome_Rater.print_TomeRater_users()`

**Comment by rishayd** [comment]
I have made the corrections and re-uploaded a new file called TomeRaterFinalCorrected.
Thank you so much for all your help and I hope the code works well this time.
