### ISSUE TITLE
Your Score

### ISSUE THREAD

**Issue by zjedwin** [rishaythegreat/pwp-capstones#2]
### Criteria 1: Valid Python Code
* _Score Level:_ 1 (Does Not Meet Expectations)
* _Comment(s):_ Code runs with errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code produces the suite of functions and classes required of it and calls them in an appropriate order.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code uses language features appropriately. If a task can be solved with a Python language feature, it is.
 
### Overall Score: 13/16
Overall, you seem to have known what you were doing and implemented the functionality more or less well, however, there were too many coding errors to excuse. You can see a list of some [here](https://github.com/rishaythegreat/pwp-capstones/issues/1).

**Comment by rishayd** [comment]
Thank you for your comments!
